import Head from "next/head";
import React from "react";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import { useCtrlContext } from "../../hooks/useCtrlContext";



const Search = () => {
const {searchedMovies}=useCtrlContext()
  return (
    <div className="h-screen">
      <Head>
        <title>Movex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header  />
      <div className=" flex flex-col my-4 mx-2 ">
      <pre>{JSON.stringify(searchedMovies,null,2)}</pre>
        <div className="bg-neutral-900/70 rounded-lg col-span-2">jj</div>
      </div>
      <Footer />
    </div>
  );
};

export default Search;
