import Head from "next/head";
import React from "react";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import Modal from "../../components/Modal";
import Results from "../../components/Results";
import { useCtrlContext } from "../../hooks/useCtrlContext";

import { useRouter } from "next/router";
import { useEffect } from "react";
import getConfig from "next/config";
import { useState } from "react";
import { useAuthContext } from "../../hooks/useAuthContext";

const { publicRuntimeConfig } = getConfig();

const Search = () => {
  const { showModal } = useCtrlContext();
  const { user } = useAuthContext();
  const [movies, setMovies] = useState([]);
  const router = useRouter();
  // const [query, setQuery] = useState("");

  // console.log(query);
  const { query } = router.query;
  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(
        `https://api.themoviedb.org/3/search/movie?api_key=${publicRuntimeConfig.apiKey}&language=en-US&query=${query}&page=1&include_adult=false`
      );
      const data = await response.json();
      setMovies(data.results);
      // setQuery(query);
    };
    fetchData();
    console.log(movies);
  }, [query, movies]);

  return  (
    query && (
      <>
        <div className="h-screen">
          <Head>
            <title>Movex</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          <div className=" flex flex-col my-4 mx-2 ">
            {/* <pre>{JSON.stringify(searchedMovies,null,2)}</pre> */}
            <div className="bg-neutral-900/70 rounded-lg w-full h-10 pl-10 pt-2">
              Results for : {query}
            </div>
            <Results results={movies} />
          </div>
          <Footer />
        </div>
        {showModal && <Modal />}
      </>
    )
  )
};

export default Search;
