import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import requests from "../utils/requests";
import Modal from "../components/Modal";
import { useCtrlContext } from "../hooks/useCtrlContext";
import { useAuthContext } from "../hooks/useAuthContext";

export default function Discover({ results }) {
  const { showModal } = useCtrlContext();
  const { authIsReady, user } = useAuthContext();

  return (
    authIsReady && (
      <>
        <div className="min-h-screen ">
          <Head>
            <title>Movex</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          <Navbar />
          <Results results={results} />
          <Footer />
        </div>
        { showModal && <Modal />}
      </>
    )
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const response = await fetch(
    `${requests[genre]?.url || requests.fetchTrending.url}`
  );
  const request = await response.json();

  return {
    props: {
      results: request.results,
    },
  };
}
