import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import requests from "../utils/requests";
import Row from "../components/Row";
import Plateforms from "../components/Plateforms";
import Footer from "../components/Footer";
import { useAuthContext } from "../hooks/useAuthContext";
import Modal from "../components/Modal";
import { useCtrlContext } from "../hooks/useCtrlContext";

export default function Home({ trending, topRated }) {
  const { showModal } = useCtrlContext();
  const { authIsReady } = useAuthContext();
  return (
    authIsReady && (
      <div className="  relative h-screen bg-gradient-to-b overflow-x-hidden">
        <Head>
          <title>Home - Movex</title>
          <meta name="movie app" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main>
          <Banner />
          <section className=" flex flex-col space-y-2   mt-[50vh] xl:mt-[60vh] left-8 sm:left">
            <Row title="Trending" results={trending} />
            <Row title="Top Rated" results={topRated} />
          </section>
        </main>

        <Plateforms />
       
        <Footer />
        {showModal && <Modal />}
      </div>
    )
  );
}

export const getServerSideProps = async () => {
  //
  const trendingData = await fetch(requests.fetchTrending.url).then((res) =>
    res.json()
  );
  const topRatedData = await fetch(requests.fetchTopRated.url).then((res) =>
    res.json()
  );

  return {
    props: {
      trending: trendingData.results,
      topRated: topRatedData.results,
    },
  };
};
