import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import requests from "../utils/requests";
import Row from "../components/Row";

export default function Home({ trending }) {
  // console.log(trending);
  return (
    <div className="  relative h-screen bg-gradient-to-b overflow-x-hidden">
      <Head>
        <title>Home - Movex</title>
        <meta name="movie app" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Banner />
        <section className="absolute top-[65%] left-8 sm:left-10">
          <Row title="Trending" results={trending} />
        </section>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  //
  const response = await fetch(requests.fetchTrending);
  const trendingData = await response.json();

  return {
    props: {
      trending: trendingData.results,
    },
  };
};
