import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Modal from "../components/Modal";
import Results from "../components/Results";
import { useAuthContext } from "../hooks/useAuthContext";
import { useCtrlContext } from "../hooks/useCtrlContext";

export default function Watchlist() {
  const { authIsReady } = useAuthContext();
  const {watchList,showModal}=useCtrlContext()


  return (
    authIsReady && (
      <>
        <div className="h-screen">
          <Head>
            <title>Movex-Watchlist</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          <Results results={watchList} />
          <Footer />
        </div>
         {showModal && <Modal />}
      </>
      
    )
  );
}
