import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Modal from "../components/Modal";
import Results from "../components/Results";
import { useAuthContext } from "../hooks/useAuthContext";
import { useCollection } from "../hooks/useCollection";
import { useCtrlContext } from "../hooks/useCtrlContext";

export default function Watchlist() {
  const { authIsReady, user } = useAuthContext();
  const { showModal } = useCtrlContext();
  const { documents, error } = useCollection(
    "watchlist",
    ["uid", "==", user.uid],
    ["createdAt", "desc"]
  );
  let watchlist = [];
  if (documents) {
    watchlist = documents.map((doc) => doc.movie);
  }
  return (
    user &&
    authIsReady && (
      <>
        <div className="h-screen">
          <Head>
            <title>Movex-Watchlist</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          {watchlist.length > 0 ? (
            <Results results={watchlist} />
          ) : (
            <p className="h-full">
              add movies to your watchlist and come back anytime to find them
              here
            </p>
          )}
          <Footer />
        </div>
        {showModal && <Modal />}
      </>
    )
  );
}
